version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - './.env.${STAGE:-dev}'
    # environment:
    #   POSTGRES_PASSWORD: postgres

  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    env_file:
      - './.env.${STAGE:-dev}'
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
